targetScope = 'resourceGroup'

@description('Azure region for all resources. Use a region where Azure Managed Grafana is available.')
param location string = resourceGroup().location

@description('Short prefix used in resource names. It is normalized to lowercase. Keep it globally distinctive.')
@minLength(3)
@maxLength(16)
param namePrefix string

@description('Log Analytics retention in days.')
@minValue(30)
@maxValue(730)
param retentionInDays int = 30

@description('Daily ingestion cap in GB. Use -1 for no cap.')
@minValue(-1)
param dailyQuotaGb int = 1

@description('Tags applied to all resources.')
param tags object = {
  workload: 'github-copilot-monitoring'
}

var namePrefixNormalized = toLower(namePrefix)
var workspaceName = '${namePrefixNormalized}-law'
var appInsightsName = '${namePrefixNormalized}-appi'
var grafanaName = '${namePrefixNormalized}-grafana'
var monitoringReaderRoleDefinitionId = subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '43d0d8ad-25c7-4714-9337-8ba259a9fe05')

resource workspace 'Microsoft.OperationalInsights/workspaces@2023-09-01' = {
  name: workspaceName
  location: location
  tags: tags
  properties: {
    features: {
      disableLocalAuth: true
      enableLogAccessUsingOnlyResourcePermissions: true
    }
    publicNetworkAccessForIngestion: 'Enabled'
    publicNetworkAccessForQuery: 'Enabled'
    retentionInDays: retentionInDays
    sku: {
      name: 'PerGB2018'
    }
    workspaceCapping: {
      dailyQuotaGb: dailyQuotaGb
    }
  }
}

resource appInsights 'Microsoft.Insights/components@2020-02-02' = {
  name: appInsightsName
  location: location
  kind: 'web'
  tags: tags
  properties: {
    Application_Type: 'web'
    DisableIpMasking: false
    DisableLocalAuth: false
    Flow_Type: 'Bluefield'
    IngestionMode: 'LogAnalytics'
    Request_Source: 'rest'
    RetentionInDays: retentionInDays
    SamplingPercentage: 100
    WorkspaceResourceId: workspace.id
    publicNetworkAccessForIngestion: 'Enabled'
    publicNetworkAccessForQuery: 'Enabled'
  }
}

resource grafana 'Microsoft.Dashboard/grafana@2023-09-01' = {
  name: grafanaName
  location: location
  tags: tags
  identity: {
    type: 'SystemAssigned'
  }
  sku: {
    name: 'Standard'
  }
  properties: {
    apiKey: 'Disabled'
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
    deterministicOutboundIP: 'Disabled'
    grafanaMajorVersion: '11'
    publicNetworkAccess: 'Enabled'
    zoneRedundancy: 'Disabled'
  }
}

resource grafanaMonitoringReader 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(resourceGroup().id, grafana.id, 'monitoring-reader')
  scope: resourceGroup()
  properties: {
    principalId: grafana.identity.principalId
    principalType: 'ServicePrincipal'
    roleDefinitionId: monitoringReaderRoleDefinitionId
  }
}

output grafanaResourceName string = grafana.name
output grafanaEndpoint string = grafana.properties.endpoint
output logAnalyticsWorkspaceName string = workspace.name
output applicationInsightsName string = appInsights.name

@secure()
output applicationInsightsConnectionString string = appInsights.properties.ConnectionString
