// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepoSyncRadar.Core.Data;

#nullable disable

namespace RepoSyncRadar.Core.Migrations
{
    [DbContext(typeof(RadarDbContext))]
    partial class RadarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("RepoSyncRadar.Core.Models.BoostRule", b =>
                {
                    b.Property<string>("Pattern")
                        .HasColumnType("TEXT");

                    b.Property<double>("Delta")
                        .HasColumnType("REAL");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.HasKey("Pattern");

                    b.ToTable("BoostRules");
                });

            modelBuilder.Entity("RepoSyncRadar.Core.Models.Commit", b =>
                {
                    b.Property<string>("Sha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AuthoredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PrNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Sha");

                    b.HasIndex("AuthoredAt");

                    b.HasIndex("PrNumber");

                    b.ToTable("Commits");
                });

            modelBuilder.Entity("RepoSyncRadar.Core.Models.CommitFile", b =>
                {
                    b.Property<string>("Sha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<int>("Additions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Deletions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Sha", "Path");

                    b.HasIndex("Path");

                    b.ToTable("CommitFiles");
                });

            modelBuilder.Entity("RepoSyncRadar.Core.Models.CopilotToolLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArgsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("ToolName");

                    b.ToTable("CopilotToolLogs");
                });

            modelBuilder.Entity("RepoSyncRadar.Core.Models.Draft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Posted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PostedUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Sha", "Channel");

                    b.ToTable("Drafts");
                });

            modelBuilder.Entity("RepoSyncRadar.Core.Models.IgnoreRule", b =>
                {
                    b.Property<string>("Pattern")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.HasKey("Pattern");

                    b.ToTable("IgnoreRules");
                });

            modelBuilder.Entity("RepoSyncRadar.Core.Models.PathUrlMap", b =>
                {
                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Path", "Version", "Language");

                    b.ToTable("PathUrlMaps");
                });

            modelBuilder.Entity("RepoSyncRadar.Core.Models.Review", b =>
                {
                    b.Property<string>("Sha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Sha");

                    b.HasIndex("Status");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("RepoSyncRadar.Core.Models.Scoring", b =>
                {
                    b.Property<string>("Sha")
                        .HasColumnType("TEXT");

                    b.Property<string>("AudienceJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsJa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ScoredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryJa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WhyJa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Sha");

                    b.HasIndex("Score");

                    b.ToTable("Scorings");
                });

            modelBuilder.Entity("RepoSyncRadar.Core.Models.CommitFile", b =>
                {
                    b.HasOne("RepoSyncRadar.Core.Models.Commit", null)
                        .WithMany("Files")
                        .HasForeignKey("Sha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RepoSyncRadar.Core.Models.Draft", b =>
                {
                    b.HasOne("RepoSyncRadar.Core.Models.Commit", null)
                        .WithMany("Drafts")
                        .HasForeignKey("Sha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RepoSyncRadar.Core.Models.Review", b =>
                {
                    b.HasOne("RepoSyncRadar.Core.Models.Commit", null)
                        .WithOne("Review")
                        .HasForeignKey("RepoSyncRadar.Core.Models.Review", "Sha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RepoSyncRadar.Core.Models.Scoring", b =>
                {
                    b.HasOne("RepoSyncRadar.Core.Models.Commit", null)
                        .WithOne("Scoring")
                        .HasForeignKey("RepoSyncRadar.Core.Models.Scoring", "Sha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RepoSyncRadar.Core.Models.Commit", b =>
                {
                    b.Navigation("Drafts");

                    b.Navigation("Files");

                    b.Navigation("Review");

                    b.Navigation("Scoring");
                });
#pragma warning restore 612, 618
        }
    }
}
